# Generated by Django 4.1.3 on 2023-01-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=120)),
                ("Email", models.EmailField(max_length=100)),
                ("Phone", models.IntegerField()),
                ("Country", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=120)),
                ("Query", models.TextField()),
            ],
        ),
    ]
